services:
    core.service.product_manager:
        class: CoreBundle\Service\Repository\ProductManager
        arguments: ['@doctrine.orm.entity_manager']
    core.service.product.size_manager:
            class: CoreBundle\Service\Repository\ProductSizeManager
            arguments: ['@doctrine.orm.entity_manager', '@core.service.product_manager']
    core.service.image_manager:
                class: CoreBundle\Service\Repository\ImageManager
                arguments: ['@doctrine.orm.entity_manager', '@core.service.product_manager']
    core.service.category_manager:
                class: CoreBundle\Service\Repository\CategoryManager
                arguments: ['@doctrine.orm.entity_manager']
<<<<<<< HEAD
    core.service.alert_manager:
                    class: CoreBundle\Service\Repository\AlertManager
                    arguments: ['@doctrine.orm.entity_manager']
=======
    core.service.brand_manager:
                class: CoreBundle\Service\Repository\BrandManager
                arguments: ['@doctrine.orm.entity_manager']
    core.service.brand.image_manager:
                class: CoreBundle\Service\Repository\BrandImageManager
                arguments: ['@doctrine.orm.entity_manager','@core.service.brand_manager']
>>>>>>> 2ece1a45e961d14b0cda756b99ac30fa83f888ad



