admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Admin:index }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
admin_category_list:
    path:     /admin/category
    defaults: { _controller: AdminBundle:Category:list }

admin_category_add:
    path:     /admin/category/add
    defaults: { _controller: AdminBundle:Category:add }

admin_category_edit:
    path:     /admin/category/edit/{id}
    defaults:
            _controller: AdminBundle:Category:edit
            requirements:
            id: \d+

admin_category_delete:
    path:     /admin/category/delete/{id}
    defaults:
            _controller: AdminBundle:Category:delete
            requirements:
            id: \d+

admin_product_list:
    path:     /admin/products
    defaults: { _controller: AdminBundle:Product:list }

admin_product_add:
    path:     /admin/product/add
    defaults: { _controller: AdminBundle:Product:add }

admin_product_edit:
    path:     /admin/product/edit/{id}
    defaults:
            _controller: AdminBundle:Product:edit
            requirements:
            id: \d+

admin_product_delete:
    path:     /admin/product/delete/{id}
    defaults:
            _controller: AdminBundle:Product:delete
            requirements:
            id: \d+
admin_product_image_add:
    path:     /admin/product/image/add/{id}
    defaults:
            _controller: AdminBundle:Image:add
            requirements:
            id: \d+
admin_product_size_add:
    path:     /admin/product/size/add/{id}
    defaults:
            _controller: AdminBundle:ProductSize:add
            requirements:
            id: \d+
admin_product_image_edit:
    path:     /admin/product/image/edit/{idp}/{id}
    defaults:
            _controller: AdminBundle:Image:edit
            requirements:
            id: \d+
            idp: \d+
            
admin_product_image_delete:
    path:     /admin/product/image/delete/{idp}/{id}
    defaults:
            _controller: AdminBundle:Image:delete
            requirements:
            id: \d+
            idp: \d+
admin_product_image_list:
    path:     /admin/product/image/list/{id}
    defaults:
            _controller: AdminBundle:Image:list
            requirements:
            id: \d+
admin_product_size_edit:
    path:     /admin/product/size/edit/{idp}/{id}
    defaults:
            _controller: AdminBundle:ProductSize:edit
            requirements:
            id: \d+
            idp: \d+
admin_product_size_list:
    path:     /admin/product/size/list/{id}
    defaults:
            _controller: AdminBundle:ProductSize:list
            requirements:
            id: \d+
admin_product_size_delete:
    path:     /admin/product/size/delete/{idp}/{id}
    defaults:
            _controller: AdminBundle:ProductSize:delete
            requirements:
            id: \d+
            idp: \d+
admin_product_show:
    path:     /admin/product/{id}
    defaults:
            _controller: AdminBundle:Product:show
            requirements:
            id: \d+
admin_brand_list:
    path:     /admin/brand
    defaults: { _controller: AdminBundle:Brand:list }
admin_brand_add:
    path:     /admin/brand/add
    defaults: { _controller: AdminBundle:Brand:add }

admin_alert_add:
    path:     /admin/alert/add
    defaults: { _controller: AdminBundle:Alert:add }
admin_alert_show:
    path:     /admin/alert/show
    defaults: { _controller: AdminBundle:Alert:list }
admin_alert_edit:
    path:     /admin/alert/edit/{id}
    defaults:
            _controller: AdminBundle:Alert:edit
            requirements:
            id: \d+
admin_promotion_add:
    path:     /admin/promotion/add
    defaults: { _controller: AdminBundle:Promotion:add }
admin_brand_edit:
        path:     /admin/brand/edit/{id}
        defaults:
                _controller: AdminBundle:Brand:edit
                requirements:
                id: \d+
admin_brand_show:
    path:     /admin/brand/{id}
    defaults:
            _controller: AdminBundle:Brand:show
            requirements:
            id: \d+
admin_brand_delete:
    path:     /admin/brand/delete/{id}
    defaults:
            _controller: AdminBundle:Brand:delete
            requirements:
            id: \d+
admin_promotion_list:
    path:     /admin/promotion/list
    defaults: { _controller: AdminBundle:Promotion:list }
admin_promotion_edit:
        path:     /admin/promotion/edit/{id}
        defaults:
                _controller: AdminBundle:Promotion:edit
                requirements:
                id: \d+
admin_product_promotion:
        path:     /admin/product/{id}/promotions
        defaults:
                _controller: AdminBundle:Product:promotion
                requirements:
                id: \d+
admin_user_add:
    path:     /admin/user/add
    defaults: { _controller: AdminBundle:User:add }
admin_user_list:
    path:     /admin/user/list
    defaults: { _controller: AdminBundle:User:index }