admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Admin:index }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
admin_category_list:
    path:     /admin/categories
    defaults: { _controller: AdminBundle:Category:index }

admin_category_add:
    path:     /admin/category/add
    defaults: { _controller: AdminBundle:Category:add }

admin_category_edit:
    path:     /admin/category/edit/{id}
    defaults:
            _controller: AdminBundle:Category:edit
            requirements:
            id: \d+

admin_category_delete:
    path:     /admin/category/delete/{id}
    defaults:
            _controller: AdminBundle:Category:delete
            requirements:
            id:
admin_category_disable:
    path:     /admin/category/disable/{id}
    defaults:
            _controller: AdminBundle:Category:disable
            requirements:
            id:

admin_category_enable:
        path:     /admin/category/enable/{id}
        defaults:
                _controller: AdminBundle:Category:enable
                requirements:
                id: \d+
admin_category_product_list:
    path:     /admin/category/{id}/products
    defaults: { _controller: AdminBundle:Category:getProducts }

admin_product_list:
    path:     /admin/products
    defaults: { _controller: AdminBundle:Product:index }

admin_product_add:
    path:     /admin/product/add
    defaults: { _controller: AdminBundle:Product:add }

admin_product_edit:
    path:     /admin/product/edit/{id}
    defaults:
            _controller: AdminBundle:Product:edit
            requirements:
            id: \d+

admin_product_disable:
    path:     /admin/product/disable/{id}
    defaults:
            _controller: AdminBundle:Product:disable
            requirements:
            id: \d+
admin_product_enable:
        path:     /admin/product/enable/{id}
        defaults:
                _controller: AdminBundle:Product:enable
                requirements:
                id: \d+
admin_product_delete:
    path:     /admin/product/delete/{id}
    defaults:
            _controller: AdminBundle:Product:delete
            requirements:
            id: \d+
admin_product_show:
    path:     /admin/product/{id}
    defaults:
            _controller: AdminBundle:Product:show
            requirements:
            id: \d+
admin_product_image_add:
    path:     /admin/product/image/add/{id}
    defaults:
            _controller: AdminBundle:Image:add
            requirements:
            id: \d+
admin_product_size_add:
    path:     /admin/product/size/add/{id}
    defaults:
            _controller: AdminBundle:Size:add
            requirements:
            id: \d+
admin_product_image_edit:
    path:     /admin/product/image/edit/{idp}/{id}
    defaults:
            _controller: AdminBundle:Image:edit
            requirements:
            id: \d+
            idp: \d+
            
admin_product_image_delete:
    path:     /admin/product/image/delete/{idp}/{id}
    defaults:
            _controller: AdminBundle:Image:delete
            requirements:
            id: \d+
            idp: \d+
admin_product_image_disable:
    path:     /admin/product/image/disable/{idp}/{id}
    defaults:
            _controller: AdminBundle:Image:disable
            requirements:
            id: \d+
            idp: \d+
admin_product_image_enable:
    path:     /admin/product/image/enable/{idp}/{id}
    defaults:
            _controller: AdminBundle:Image:enable
            requirements:
            id: \d+
            idp: \d+
admin_product_image_list:
    path:     /admin/product/image/list/{id}
    defaults:
            _controller: AdminBundle:Image:index
            requirements:
            id: \d+
admin_product_size_edit:
    path:     /admin/product/size/edit/{idp}/{id}
    defaults:
            _controller: AdminBundle:Size:edit
            requirements:
            id: \d+
            idp: \d+
admin_product_size_list:
    path:     /admin/product/size/list/{id}
    defaults:
            _controller: AdminBundle:Size:index
            requirements:
            id: \d+
admin_product_size_disable:
    path:     /admin/product/size/disable/{idp}/{id}
    defaults:
            _controller: AdminBundle:Size:disable
            requirements:
            id: \d+
            idp: \d+
admin_product_size_enable:
    path:     /admin/product/size/enable/{idp}/{id}
    defaults:
            _controller: AdminBundle:Size:enable
            requirements:
            id: \d+
            idp: \d+
admin_product_size_delete:
    path:     /admin/product/size/delete/{idp}/{id}
    defaults:
            _controller: AdminBundle:Size:delete
            requirements:
            id: \d+
            idp: \d+

admin_brand_list:
    path:     /admin/brands
    defaults: { _controller: AdminBundle:Brand:index }

admin_brand_add:
    path:     /admin/brand/add
    defaults: { _controller: AdminBundle:Brand:add }

admin_brand_enable:
        path:     /admin/brand/enable/{id}
        defaults:
                _controller: AdminBundle:Brand:enable
                requirements:
                id: \d+
admin_brand_edit:
        path:     /admin/brand/edit/{id}
        defaults:
                _controller: AdminBundle:Brand:edit
                requirements:
                id: \d+
admin_brand_show:
    path:     /admin/brand/{id}
    defaults:
            _controller: AdminBundle:Brand:show
            requirements:
            id: \d+
admin_brand_delete:
    path:     /admin/brand/delete/{id}
    defaults:
            _controller: AdminBundle:Brand:delete
            requirements:
            id: \d+
admin_brand_disable:
    path:     /admin/brand/disable/{id}
    defaults:
            _controller: AdminBundle:Brand:disable
            requirements:
            id: \d+

admin_alert_add:
    path:     /admin/alert/add
    defaults: { _controller: AdminBundle:Alert:add }
admin_alert_show:
    path:     /admin/alert/show
    defaults: { _controller: AdminBundle:Alert:list }
admin_alert_edit:
    path:     /admin/alert/edit/{id}
    defaults:
            _controller: AdminBundle:Alert:edit
            requirements:
            id: \d+
admin_promotion_add:
    path:     /admin/promotion/add
    defaults: { _controller: AdminBundle:Promotion:add }
admin_promotion_list:
    path:     /admin/promotion/list
    defaults: { _controller: AdminBundle:Promotion:list }
admin_promotion_edit:
        path:     /admin/promotion/edit/{id}
        defaults:
                _controller: AdminBundle:Promotion:edit
                requirements:
                id: \d+
admin_product_promotion:
        path:     /admin/product/{id}/promotions
        defaults:
                _controller: AdminBundle:ProductService:promotion
                requirements:
                id: \d+
admin_user_add:
    path:     /admin/user/add
    defaults: { _controller: AdminBundle:User:add }
admin_user_change_password:
    path:     /admin/user/change-password
    defaults: { _controller: AdminBundle:User:changePassword }

admin_user_list:
    path:     /admin/users
    defaults: { _controller: AdminBundle:User:index }
admin_user_edit:
        path:     /admin/user/edit/{id}
        defaults:
                _controller: AdminBundle:User:edit
                requirements:
                id: \d+
admin_user_delete:
        path:     /admin/user/delete/{id}
        defaults:
                _controller: AdminBundle:User:delete
                requirements:
                id: \d+
admin_user_disable:
        path:     /admin/user/disable/{id}
        defaults:
                _controller: AdminBundle:User:disable
                requirements:
                id: \d+
admin_user_enable:
        path:     /admin/user/enable/{id}
        defaults:
                _controller: AdminBundle:User:enable
                requirements:
                id: \d+
admin_access_denied:
    path:     /admin/access_denied
    defaults: { _controller: AdminBundle:Admin:accessDenied }

admin_customer_list:
    path:     /admin/customers
    defaults: { _controller: AdminBundle:Customer:index }

admin_customer_disable:
        path:     /admin/customer/disable/{id}
        defaults:
                _controller: AdminBundle:Customer:disable
                requirements:
                id: \d+
admin_order_list:
    path:     /admin/orders
    defaults: { _controller: AdminBundle:Order:index }
admin_order_disable:
        path:     /admin/order/disable/{id}
        defaults:
                _controller: AdminBundle:Order:disable
                requirements:
                id: \d+
admin_order_edit:
        path:     /admin/order/edit/{id}
        defaults:
                _controller: AdminBundle:Order:edit
                requirements:
                id: \d+
admin_order_item_list:
    path:     /admin/order/item/list/{id}
    defaults:
            _controller: AdminBundle:Item:index
            requirements:
            id: \d+
admin_stock_list:
    path:     /admin/stock
    defaults: { _controller: AdminBundle:Stock:index }
admin_stock_add:
    path:     /admin/stock/add/{id}
    defaults: { _controller: AdminBundle:Stock:add }
admin_stock_decrease:
    path:     /admin/stock/decrease/{id}
    defaults: { _controller: AdminBundle:Stock:decrease }
admin_delivery_list:
    path:     /admin/deliveries
    defaults: { _controller: AdminBundle:Delivery:index }