services:
    AdminBundle\DataFixtures\ORM\LoadUser:
        tags: [doctrine.fixture.orm]
    AdminBundle\DataFixtures\ORM\LoadProduct:
            tags: [doctrine.fixture.orm]
    AdminBundle\DataFixtures\ORM\LoadColor:
                tags: [doctrine.fixture.orm]