services:
    AdminBundle\DataFixtures\ORM\LoadUser:
        tags: [doctrine.fixture.orm]
    admin.form.registration:
        class: AdminBundle\Form\RegistrationFormType
        tags:
            - { name: form.type }