api_rest:
    resource: "@ApiRestBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Controller"
    type: annotation

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

