<?php

namespace AdminBundle\Repository;

/**
 * BrandImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandImageRepository extends \Doctrine\ORM\EntityRepository
{
}
