<?php

namespace CoreBundle\Repository;

/**
 * ColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllColors($value){

	        $qb = $this->createQueryBuilder('c');
	        $qb
	            ->where('c.deleted = :deleted')
	            ->setParameter('deleted', $value) ;
	        return $qb;
	}
}
