<?php

namespace CoreBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourner la liste  des marques actives
     * return array
     */
    public function getActiveBrands()
    {
        $qb = $this->createQueryBuilder('b');
        $qb
            ->where('b.deleted =false');
        return $qb->getQuery()
            ->getResult();
    }
}
