<?php

namespace CoreBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourner la liste  des marques selon la variable $active
     * $active contenir 2 valeur true ou false
     * return array
     */
    public function getActiveBrands($active)
    {
        $qb = $this->createQueryBuilder('b');
        $qb
            ->where('b.deleted =:active')
            ->setParameter('active', $active)
        ;
        return $qb->getQuery()
            ->getResult();
    }
}
