<?php

namespace CoreBundle\Repository;

/**
 * categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

	class categoryRepository extends \Doctrine\ORM\EntityRepository
{
        /**
         * Retourner la liste  des categories actives
         * return array
         */
        public function getActiveCategories()
        {
            $qb = $this->createQueryBuilder('c');
            $qb
                ->where('c.deleted =false');
            return $qb->getQuery()
                ->getResult();
        }
}
