<?php

namespace CoreBundle\Repository;

/**
 * categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryRepository extends \Doctrine\ORM\EntityRepository
{


	public function findCategories($value)
	{
	    $qb = $this->createQueryBuilder('c');

        $qb
        ->where('c.deleted = :deleted')
         ->setParameter('deleted', $value) ;

        return $qb->getQuery()->getResult();


	}

    
}
