<?php

namespace CoreBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourner la liste  des commandes selon la variable $active
     * $active contenir 2 valeur true ou false
     * return array
     */
    public function getActiveOrders($active,$id)
    {
        $qb = $this->createQueryBuilder('o');
        $qb
            ->andWhere('o.deleted =:active')
            ->andWhere('o.customer =:id')
            ->setParameter('active', $active)
            ->setParameter('id', $id)
            ->orderBy('o.id', 'DESC');
        ;
        return $qb->getQuery()
            ->getResult();
    }

}
