<?php

namespace CoreBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourner la liste  des produist actives
     * return array
     */
    public function getActiveProducts()
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->where('p.deleted =false');
        return $qb->getQuery()
            ->getResult();
    }
}
