<?php

namespace CoreBundle\Repository;

/**
 * ProductSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSizeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourner la liste  des tailles actives
     * return array
     */
    public function getActiveSizes()
    {
        $qb = $this->createQueryBuilder('s');
        $qb
            ->where('s.deleted =false');
        return $qb->getQuery()
            ->getResult();
    }
}
