<?php

namespace CoreBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProducts($value){

        $qb = $this->createQueryBuilder('p');
        $qb
            ->where('p.deleted = :deleted')
            ->setParameter('deleted', $value) ;
        return $qb->getQuery()->getResult();
    }
}
